"""Canonical shared record schemas for CLIO services."""

from __future__ import annotations

from clio_schemas.a2ui.sidecar import CatalogSidecar
from clio_schemas.a2ui.v0_9_1.bounded_components import COMPONENT_MODELS
from clio_schemas.a2ui.v0_9_1.capabilities import A2UIAgentCapabilities, A2UIClientCapabilities
from clio_schemas.a2ui.v0_9_1.catalog_file import CatalogFile, FunctionDefinition
from clio_schemas.a2ui.v0_9_1.data_model import A2UIClientDataModel
from clio_schemas.a2ui.v0_9_1.messages import (
    A2UIClientAction,
    A2UIClientMessage,
    A2UIGenericError,
    A2UIServerMessage,
    A2UIValidationError,
)
from clio_schemas.constants import LOCKED_PYDANTIC_VERSION
from clio_schemas.gact_v3 import MessageBlock
from clio_schemas.model_capabilities import (
    CapabilityTag,
    DomainTag,
    FlagTag,
    ModalityTag,
    ModelCapabilityTags,
    ModelTypeTag,
    RoleTag,
    TagEvidence,
    TaskTag,
)
from clio_schemas.model_facts import (
    DescriptionFact,
    DescriptionLink,
    DescriptionValue,
    ModelFacts,
    ParametersFact,
    ParametersValue,
    Price,
    PricingAlternative,
    PricingFact,
    PricingValue,
    RecentFact,
    ReleaseDateFact,
    ReleaseDateValue,
)
from clio_schemas.models import (
    EXPORTED_MODELS,
    RESERVED_KINDS,
    AgentRole,
    ArtifactKind,
    ArtifactRecord,
    ArtifactVersion,
    ClioSchemaBase,
    Custody,
    EdgeEvidence,
    EdgeRole,
    EnvironmentRecord,
    EnvironmentTier,
    EvidenceClass,
    IdentityEvidence,
    Instrument,
    LegacyToleranceBase,
    Mechanism,
    ProvEdge,
    ReplayContract,
    TransformKind,
    TransformRecord,
    TransformStatus,
    new_artifact_id,
)

__all__ = [
    "A2UIAgentCapabilities",
    "A2UIClientAction",
    "A2UIClientCapabilities",
    "A2UIClientDataModel",
    "A2UIClientMessage",
    "A2UIGenericError",
    "A2UIServerMessage",
    "A2UIValidationError",
    "AgentRole",
    "ArtifactKind",
    "ArtifactRecord",
    "ArtifactVersion",
    "COMPONENT_MODELS",
    "CapabilityTag",
    "CatalogFile",
    "CatalogSidecar",
    "ClioSchemaBase",
    "Custody",
    "DescriptionFact",
    "DescriptionLink",
    "DescriptionValue",
    "DomainTag",
    "EXPORTED_MODELS",
    "EdgeEvidence",
    "EdgeRole",
    "EnvironmentRecord",
    "EnvironmentTier",
    "EvidenceClass",
    "FlagTag",
    "FunctionDefinition",
    "IdentityEvidence",
    "Instrument",
    "LOCKED_PYDANTIC_VERSION",
    "LegacyToleranceBase",
    "Mechanism",
    "MessageBlock",
    "ModalityTag",
    "ModelCapabilityTags",
    "ModelFacts",
    "ModelTypeTag",
    "ParametersFact",
    "ParametersValue",
    "Price",
    "PricingAlternative",
    "PricingFact",
    "PricingValue",
    "ProvEdge",
    "RESERVED_KINDS",
    "RecentFact",
    "ReleaseDateFact",
    "ReleaseDateValue",
    "ReplayContract",
    "RoleTag",
    "TagEvidence",
    "TaskTag",
    "TransformKind",
    "TransformRecord",
    "TransformStatus",
    "__version__",
    "new_artifact_id",
]

# Exact-pin lockstep versioning (see README "Versioning policy").
__version__ = "0.4.0"
