#!/usr/bin/env node
// Deterministic TypeScript generator for clio-schemas.
//
// Reads a directory of committed JSON Schema files (produced/copied by
// `python -m clio_schemas.export`) and writes a TypeScript module graph:
//
//   _models.ts        All declarations, generated ONCE from the aggregate
//                     schema (index.json). Shared definitions (enums, nested
//                     models) appear exactly once — no duplication.
//   <model>.ts        One thin re-export module per exported model, importing
//                     the model's own type plus any shared/nested types it
//                     references from ./_models. Pure re-exports, no new
//                     declarations.
//   index.ts          Barrel: `export * from "./_models"`.
//
// This layout gives per-model entry points (stable imports) while guaranteeing
// no duplicate exported declarations across the barrel.
//
// Output is deterministic: fixed banner (no timestamp), sorted file order,
// pinned formatting, and CRLF->LF normalisation.
//
// Usage:
//   node schemas-to-ts.mjs --in <schema-dir> --out <ts-dir>

import { readdirSync, readFileSync, mkdirSync, writeFileSync, rmSync } from "node:fs";
import { basename, join, resolve } from "node:path";
import { compile } from "json-schema-to-typescript";

const AGGREGATE_FILE = "index.json";
const HASHES_FILE = "HASHES.json";
const MODELS_MODULE = "_models";

function parseArgs(argv) {
  const args = { in: null, out: null };
  for (let i = 0; i < argv.length; i += 1) {
    const arg = argv[i];
    if (arg === "--in") {
      args.in = argv[(i += 1)];
    } else if (arg === "--out") {
      args.out = argv[(i += 1)];
    } else {
      throw new Error(`Unknown argument: ${arg}`);
    }
  }
  if (!args.in || !args.out) {
    throw new Error("Both --in <schema-dir> and --out <ts-dir> are required.");
  }
  return args;
}

// Fixed banner so generated files carry stable, greppable provenance and never
// leak a timestamp (which would break determinism).
const BANNER = [
  "/* eslint-disable */",
  "/**",
  " * This file was automatically generated by clio-schemas (tools/ts-gen).",
  " * DO NOT EDIT BY HAND. Regenerate from the exported JSON Schema instead:",
  " *   node schemas-to-ts.mjs --in <schema-dir> --out <ts-dir>",
  " */",
].join("\n");

const REEXPORT_BANNER = `${BANNER}\n`;

// Pinned, fully-specified options so output does not depend on library
// defaults drifting between versions.
const COMPILE_OPTIONS = {
  bannerComment: BANNER,
  additionalProperties: false,
  declareExternallyReferenced: true,
  enableConstEnums: false,
  format: true,
  strictIndexSignatures: true,
  style: {
    bracketSpacing: true,
    printWidth: 100,
    semi: true,
    singleQuote: false,
    tabWidth: 2,
    trailingComma: "none",
    useTabs: false
  }
};

function normalize(ts) {
  return ts.replace(/\r\n/g, "\n");
}

// json-schema-to-typescript treats a `$ref` that carries sibling keywords
// (pydantic emits `default`/`description` next to `$ref` at use sites) as a
// brand-new schema and generates a DUPLICATE named type (e.g. ProbeKind and
// ProbeKind1). For TypeScript we only care about the referenced type, so
// collapse any `{$ref, ...siblings}` node to a bare `{$ref}`. This is a
// type-generation-only transform; the canonical JSON Schema is untouched.
function flattenRefSiblings(node) {
  if (Array.isArray(node)) {
    return node.map(flattenRefSiblings);
  }
  if (node && typeof node === "object") {
    if (typeof node.$ref === "string") {
      return { $ref: node.$ref };
    }
    const out = {};
    for (const [key, value] of Object.entries(node)) {
      out[key] = flattenRefSiblings(value);
    }
    return out;
  }
  return node;
}

// The set of exported type names a per-model schema references: its own title
// plus every entry in its local `$defs` (shared enums / nested models). Sorted
// for deterministic output.
function referencedTypeNames(schema) {
  const names = new Set();
  if (schema.title) names.add(schema.title);
  for (const key of Object.keys(schema.$defs ?? {})) names.add(key);
  return [...names].sort();
}

async function main() {
  const args = parseArgs(process.argv.slice(2));
  const inDir = resolve(args.in);
  const outDir = resolve(args.out);

  // Always start from a clean output directory so orphaned files from a
  // previous run cannot survive (stale-artifact detection relies on this).
  rmSync(outDir, { recursive: true, force: true });
  mkdirSync(outDir, { recursive: true });

  const jsonFiles = readdirSync(inDir)
    .filter((name) => name.endsWith(".json") && name !== HASHES_FILE)
    .sort();

  if (!jsonFiles.includes(AGGREGATE_FILE)) {
    throw new Error(`Aggregate schema ${AGGREGATE_FILE} not found in ${inDir}`);
  }

  // 1. Declarations: compile the aggregate once. Shared $defs -> one decl each.
  const aggregate = flattenRefSiblings(
    JSON.parse(readFileSync(join(inDir, AGGREGATE_FILE), "utf8"))
  );
  const declarations = await compile(aggregate, aggregate.title ?? "ClioSchemaRegistry", {
    ...COMPILE_OPTIONS,
    cwd: inDir
  });
  writeFileSync(join(outDir, `${MODELS_MODULE}.ts`), normalize(declarations), "utf8");
  process.stdout.write(`wrote ${join(outDir, `${MODELS_MODULE}.ts`)}\n`);

  // 2. Per-model re-export modules (no new declarations).
  const perModel = jsonFiles.filter((name) => name !== AGGREGATE_FILE);
  for (const file of perModel) {
    const schema = JSON.parse(readFileSync(join(inDir, file), "utf8"));
    const names = referencedTypeNames(schema);
    if (names.length === 0) {
      throw new Error(`Schema ${file} has no title/$defs to re-export`);
    }
    const body =
      `${REEXPORT_BANNER}\n` +
      `export type {\n` +
      names.map((n) => `  ${n}`).join(",\n") +
      `\n} from "./${MODELS_MODULE}";\n`;
    const outPath = join(outDir, `${basename(file, ".json")}.ts`);
    writeFileSync(outPath, normalize(body), "utf8");
    process.stdout.write(`wrote ${outPath}\n`);
  }

  // 3. Barrel.
  const barrel = `${REEXPORT_BANNER}\nexport * from "./${MODELS_MODULE}";\n`;
  writeFileSync(join(outDir, "index.ts"), normalize(barrel), "utf8");
  process.stdout.write(`wrote ${join(outDir, "index.ts")}\n`);
}

main().catch((error) => {
  process.stderr.write(`${error.stack ?? error}\n`);
  process.exit(1);
});
