/* eslint-disable */
/**
 * This file was automatically generated by clio-schemas (tools/ts-gen).
 * DO NOT EDIT BY HAND. Regenerate from the exported JSON Schema instead:
 *   node schemas-to-ts.mjs --in <schema-dir> --out <ts-dir>
 */

/**
 * Opaque identifier for this batch.
 */
export type BatchId = string;
/**
 * Discriminator enum shared by more than one model.
 *
 * Exists so the bootstrap exercises enum handling through the whole
 * pydantic -> JSON Schema -> TypeScript pipeline (enums are a common source of
 * generator drift) and, because it is referenced by both `SchemaProbe` and
 * `ProbeBatch`, proves that a shared definition is emitted exactly once.
 */
export type ProbeKind = "ping" | "echo" | "noop";
/**
 * Opaque identifier for this probe record.
 */
export type ProbeId = string;
/**
 * Monotonic sequence number within a probe stream.
 */
export type Sequence = number;
/**
 * The probe records in this batch (order-significant).
 */
export type Probes = SchemaProbe[];

/**
 * Aggregate of all canonical clio-schemas records with shared definitions emitted once. Used to generate TypeScript without duplicate declarations.
 */
export interface ClioSchemaRegistry {
  ProbeBatch?: ProbeBatch;
  SchemaProbe?: SchemaProbe;
}
/**
 * Placeholder aggregate proving multi-root / shared-definition handling.
 *
 * References `SchemaProbe` (a nested model) and reuses `ProbeKind` (a shared
 * enum). The exporter emits both `ProbeKind` and `SchemaProbe` exactly once in
 * the aggregate schema, and the TypeScript generator must not duplicate their
 * declarations — the anti-duplication proof for P2.1's richer record graph.
 */
export interface ProbeBatch {
  batch_id: BatchId;
  default_kind?: ProbeKind;
  probes?: Probes;
}
/**
 * Placeholder record proving the schema export pipeline works end to end.
 *
 * Intentionally trivial; removed once the real shared records land in P2.1. It
 * carries one required string, one typed enum, and one integer with a default
 * so required/optional handling, enum generation, and defaults are all
 * exercised by the golden round-trip test.
 */
export interface SchemaProbe {
  kind?: ProbeKind;
  probe_id: ProbeId;
  sequence?: Sequence;
}
